@host = http://localhost:3000

#########
# USERS #
#########

##########
# TABLES #
##########



############
# RESERVES #
############



#########
# MENUS #
#########

GET {{host}}/api/menus

###
GET {{host}}/api/menus/2


###########
# REVIEWS #
###########