@host = http://localhost:3000


#########
# MENUS #
#########

GET {{host}}/api/menus

### GET BY ID
GET {{host}}/api/menus/4

### EDIT
PUT {{host}}/api/menus/5
Content-Type: application/json

{
    "name": "menu murlock",
    "firsts": "asf",
    "seconds": "sdfs",
    "desserts": "sdfgh",
    "price": 20
}

