@host = http://localhost:3000

GET {{host}}/api/reservations


###

GET {{host}}/api/reservations/3


###
GET {{host}}/api/reservations/date/2023-10-10


###
GET {{host}}/api/reservations/date/2023-10-10/17:00


###

POST {{host}}/api/reservations
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2NTU4MjcyfQ.7QeaD0-OXE5p079Pw7XRUeT748UeHLda00pleG0o7yA

{
    "user_id": 5,
    "table_id": 2,
    "reservation_date": "2023-10-10",
    "reservation_time": "17:00",
    "num_guests": 2,
    "special_request": "wea",
    "status": "pending"
}


###

DELETE {{host}}/api/reservations/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2NTU4MjcyfQ.7QeaD0-OXE5p079Pw7XRUeT748UeHLda00pleG0o7yA


